name: tamuq_app
description: "A digital guest book app using Flutter and Hive."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  path_provider: ^2.1.1
  csv: ^5.0.2
  intl: ^0.19.0         # ✅ Tambahkan ini

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Untuk generate file HiveAdapter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
