name: tamuq_app
description: "A digital guest book app using Flutter and Hive."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & State Management
  provider: ^6.1.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # PDF Export
  pdf: ^3.10.4
  printing: ^5.12.0

  # Chart & Dashboard
  fl_chart: ^0.64.0

  # Format & Util
  intl: ^0.18.1
  csv: ^5.0.2

  # Default Flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Hive Generator
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
