name: tamuq_app
description: "A digital guest book app using Flutter and Hive."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & State Management
  provider: ^6.1.2

  # PDF Export
  pdf: ^3.10.4
  printing: ^5.12.0

  # Chart & Dashboard
  fl_chart: ^0.64.0

  # Format & Util
  intl: ^0.18.1
  csv: ^5.0.2

  # HTTP Request
  http: ^1.1.0

  # Default Flutter
  cupertino_icons: ^1.0.8

  # ✅ Tambahan opsional untuk simpan file ke device
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpeg
